// Fill out your copyright notice in the Description page of Project Settings.

/**
 * 
 */
#include "NativeGameplayTags.h"

namespace ARPGGameplayTags
{
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_Attack);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_Execute);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_Executed);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_HitReact);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Abilities_Parry);


	//Combat 태그를 추가해 전투상태에 대한 구분을 할것.
	//Status.Combat.Parry ..
	//Status.NonCombat.Death?? 이런식??
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Parry);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack_CanNextAttack);


	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Hit);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Executed);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Execution);

	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitReact);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Block);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parry);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_OpenInventory);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_OpenEquipment);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ExitGame);


	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Default);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Strafe);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Block);


	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equipment_Weapon);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equipment_Helmet);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equipment_Armor);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equipment_Gloves);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equipment_Shoes);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Tool);

	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_RightClick);	
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LeftClick);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Crouch);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Esc);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Tab);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_MouseWheelMove);

	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Parry);
	ACTIONFRAMEWORK_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Block);


	ACTIONFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusBar_State_None);
	ACTIONFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusBar_State_Targeted);
	ACTIONFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatusBar_State_DamageResponse);

}
